### PR TITLE
Added scikit-image

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
cc @jni

re-deploying with this commit now.

**Comment by TomAugspurger** [comment]
Our conda was pretty old, so had to update that so scipy 1.0+ could be found in the new defaults channel. Hopefully that doesn't break things 😬

**Comment by TomAugspurger** [comment]
Couple of fixups. Things should be live now. http://pandas.pydata.org/speed/scikit-image/

**Comment by jni** [comment]
@TomAugspurger SO COOL.

btw, I noticed the mem examples in the asv site, but I don't see any memory profiling happening. Is that a special setting, or something that was attempted but abandoned, or...?

**Comment by TomAugspurger** [comment]
https://github.com/scikit-image/scikit-image/pull/3215 for the memory test (need to return the object being tracked)

**Pull request merged**
